services:

  filegator:
    image: filegator/filegator:latest
    container_name: filegator
    restart: unless-stopped
    ports:
      - "8280:8080"
    volumes:
      - ./files:/var/www/filegator/repository
      - ./private:/var/www/filegator/private:rw
      - ./configuration.php:/var/www/filegator/configuration.php:rw
